third home done
Oxunjon1029/budget pull request #3
Opened 2022-03-18 11:59 UTC by Oxunjon1029

2022-03-18 13:31 UTC, AudriusBaltusis requested changes

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/Subscription.js
> +  Category: {
`categoryId`

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/piggybankmodel.js
> +  Category: {
`categoryId`

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/transaction.js
> +  Category: {},
Please remove empty property

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/piggybankmodel.js
> +const mongoose = require("mongoose");
file name is not consistent

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/obligatoryPayment.js
> +  Category: {
`categoryId`

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/transaction.js
> +  account_id: {
`accountId`

2022-03-18 13:31 UTC, AudriusBaltusis commented on routes/account.js
> +    // res.send("Updated succesfully");
Please remove unused code

2022-03-18 13:31 UTC, AudriusBaltusis commented on routes/subscription.js
> +  console.log('req', req);
Please remove `console.log`

2022-03-18 13:31 UTC, AudriusBaltusis commented on server.js
> +userCreateAdmin();
This functionality shouldn't be in `server.js`

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/piggybankmodel.js
> +const PiggyBannkSchema = new mongoose.Schema({
Typo in model name

2022-03-18 13:31 UTC, AudriusBaltusis commented on models/Category.js
> +  Type:[
Could you explain this structure?

2022-03-19 14:01 UTC, Oxunjon1029 commented
In models/Category.js
<https://github.com/Oxunjon1029/budget/pull/3#discussion_r830001628>:

> @@ -0,0 +1,20 @@
+const mongoose = require("mongoose");
+
+const Category = new mongoose.Schema({
+  title:{
+    type:String,
+    required:true
+  },
+  Type:[

Could you explain this structure?:

In this case, in the category schema , we have income and expense category.
So in order to get either income category or expense category, I created
Type property like that, but I don't know whether it's true or not . Could
you help with that case?



On Fri, 18 Mar 2022 at 18:31, Audrius Baltušis ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In models/Subscription.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829995607>:
>
> > +    required: true
> +  },
> +  description: String,
> +  firstDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  lastDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  dayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  Category: {
>
> categoryId
> ------------------------------
>
> In models/piggybankmodel.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829996407>:
>
> > +    required: true
> +  },
> +  description: String,
> +  firstDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  lastDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  dayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  Category: {
>
> categoryId
> ------------------------------
>
> In models/transaction.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829996780>:
>
> > +
> +  },
> +  account_id: {
> +    type: mongoose.SchemaTypes.ObjectId,
> +    ref: 'Accounts'
> +  },
> +  title: {
> +    type: String,
> +    required: true
> +  },
> +  description: String,
> +  dateOfOperattion: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  Category: {},
>
> Please remove empty property
> ------------------------------
>
> In models/piggybankmodel.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829998017>:
>
> > @@ -0,0 +1,40 @@
> +const mongoose = require("mongoose");
>
> file name is not consistent
> ------------------------------
>
> In models/obligatoryPayment.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829998462>:
>
> > +    required: true
> +  },
> +  description: String,
> +  firstDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  lastDayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  dayOfPayment: {
> +    type: Date,
> +    default: () => Date.now()
> +  },
> +  Category: {
>
> categoryId
> ------------------------------
>
> In models/transaction.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829998702>:
>
> > @@ -0,0 +1,33 @@
> +const mongoose = require("mongoose");
> +
> +const Transaction = new mongoose.Schema({
> +  Type: {
> +
> +  },
> +  account_id: {
>
> accountId
> ------------------------------
>
> In routes/account.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829999156>:
>
> >  })
>
>
> -router.put('/edit/:id', (req, res) => {
> -
> -  res.send("Updated succesfully");
> +router.put(`/edit`, async (req, res) => {
> +  try {
> +    const account = await Account.findByIdAndUpdate(req.body._id, req.body, { new: true })
> +    res.status(200).json(account);
> +    // res.send("Updated succesfully");
>
> Please remove unused code
> ------------------------------
>
> In routes/subscription.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r829999589>:
>
> > @@ -0,0 +1,23 @@
> +const express = require("express");
> +const router = express.Router();
> +
> +router.post('/add', (req, res) => {
> +  console.log('req', req);
>
> Please remove console.log
> ------------------------------
>
> In server.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r830000184>:
>
> > @@ -72,6 +77,27 @@ app.get('/posts', auth, (req, res) => {
>    res.json(db.users.filter(user => user.role.toLowerCase() === "user"));
>  })
>
> +
> +userCreateAdmin();
>
> This functionality shouldn't be in server.js
> ------------------------------
>
> In models/piggybankmodel.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r830000986>:
>
> > @@ -0,0 +1,40 @@
> +const mongoose = require("mongoose");
> +
> +const PiggyBannkSchema = new mongoose.Schema({
>
> Typo in model name
> ------------------------------
>
> In models/Category.js
> <https://github.com/Oxunjon1029/budget/pull/3#discussion_r830001628>:
>
> > @@ -0,0 +1,20 @@
> +const mongoose = require("mongoose");
> +
> +const Category = new mongoose.Schema({
> +  title:{
> +    type:String,
> +    required:true
> +  },
> +  Type:[
>
> Could you explain this structure?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxunjon1029/budget/pull/3#pullrequestreview-914354800>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULOQHAQKJ76T6V4ZQNDIKLVASATZANCNFSM5RBUHGUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-21 07:52 UTC, AudriusBaltusis requested changes
Please add `coverage` to `.gitignore`, it shouldn't be included into PR

2022-03-21 10:51 UTC, closed without merging

2022-03-21 10:52 UTC, Oxunjon1029 commented
Done.

On Mon, 21 Mar 2022 at 12:52, Audrius Baltušis ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please add coverage to .gitignore, it shouldn't be included into PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxunjon1029/budget/pull/3#pullrequestreview-915352046>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULOQHB7JT3DJQ46GYYMPRLVBATFPANCNFSM5RBUHGUA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-21 21:03 UTC, AudriusBaltusis commented
Why this PR was closed?

2022-03-22 05:25 UTC, Oxunjon1029 commented
After adding coverage file , that happened , why is that ?

On Tue, 22 Mar 2022 at 02:03, Audrius Baltušis ***@***.***>
wrote:

> Why this PR was closed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxunjon1029/budget/pull/3#issuecomment-1074415030>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULOQHH6KW3OXDPEQTDPALDVBDPZ7ANCNFSM5RBUHGUA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-03-22 05:48 UTC, Oxunjon1029 commented
Could you help me with that ?

2022-03-22 06:22 UTC, Oxunjon1029 commented
I can't touch the reopen button below . If you can , could you reopen the pull request . I don't know how it happened .

2022-03-22 07:24 UTC, Oxunjon1029 commented
I finally reopened the pull request . Could you review all the changes and
give me feedback?


On Tue, 22 Mar 2022 at 10:25, Oxunjon Abdusalomov <
***@***.***> wrote:

> After adding coverage file , that happened , why is that ?
>
> On Tue, 22 Mar 2022 at 02:03, Audrius Baltušis ***@***.***>
> wrote:
>
>> Why this PR was closed?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Oxunjon1029/budget/pull/3#issuecomment-1074415030>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AULOQHH6KW3OXDPEQTDPALDVBDPZ7ANCNFSM5RBUHGUA>
>> .
>> You are receiving this because you modified the open/close state.Message
>> ID: ***@***.***>
>>
>