Test2
Oxunjon1029/budget pull request #4
Opened 2022-03-22 07:22 UTC by Oxunjon1029

2022-03-22 20:03 UTC, AudriusBaltusis requested changes

2022-03-22 20:03 UTC, AudriusBaltusis commented on routes/authentication.js
> +  res.send("Authenticated succesfully");
Looks like something is missing here

2022-03-22 20:03 UTC, AudriusBaltusis commented on routes/categories.js
> +  res.send("Category created succesfully");
Looks like something is missing here

2022-03-22 20:03 UTC, AudriusBaltusis commented on routes/account.js
> +  const account = await Account.find({});
this logic should be in controller. route should look like `router.get('/', Account.find)`

2022-03-22 20:03 UTC, AudriusBaltusis commented on routes/account.js
> +  try {
such routes should be protected by `auth` guard

2022-03-23 07:18 UTC, Oxunjon1029 commented
done

On Wed, 23 Mar 2022 at 01:04, Audrius Baltušis ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In routes/authentication.js
> <https://github.com/Oxunjon1029/budget/pull/4#discussion_r832571314>:
>
> > @@ -0,0 +1,9 @@
> +const express = require("express");
> +const router = express.Router();
> +
> +router.post('/',(req,res)=>{
> +  res.send("Authenticated succesfully");
>
> Looks like something is missing here
> ------------------------------
>
> In routes/categories.js
> <https://github.com/Oxunjon1029/budget/pull/4#discussion_r832571532>:
>
> > @@ -0,0 +1,22 @@
> +const express = require("express");
> +const router = express.Router();
> +
> +router.post('/add', (req, res) => {
> +  res.send("Category created succesfully");
>
> Looks like something is missing here
> ------------------------------
>
> In routes/account.js
> <https://github.com/Oxunjon1029/budget/pull/4#discussion_r832574746>:
>
> > +const router = express.Router();
> +const Account = require("../models/Accounts");
> +router.post('/add', (req, res) => {
> +  try {
> +    const account = new Account({ title: req.body.title, description: req.body.description });
> +    account.save();
> +
> +    res.status(200).json(account);
> +  } catch (err) {
> +    res.status(400).json(err.message);
> +  }
> +})
> +
> +
> +router.get('/', async (req, res) => {
> +  const account = await Account.find({});
>
> this logic should be in controller. route should look like router.get('/',
> Account.find)
> ------------------------------
>
> In routes/account.js
> <https://github.com/Oxunjon1029/budget/pull/4#discussion_r832577198>:
>
> > +
> +    res.status(200).json(account);
> +  } catch (err) {
> +    res.status(400).json(err.message);
> +  }
> +})
> +
> +
> +router.get('/', async (req, res) => {
> +  const account = await Account.find({});
> +  res.json(account)
> +})
> +
> +
> +router.put('/edit', async (req, res) => {
> +  try {
>
> such routes should be protected by auth guard
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxunjon1029/budget/pull/4#pullrequestreview-917807433>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULOQHDQX7QGDTQPL64MJ5TVBIRTFANCNFSM5RJ63EWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-23 08:49 UTC, AudriusBaltusis approved these changes

2022-03-23 13:05 UTC, merged