united test has been finished in app.component.spec.ts
Oxunjon1029/budget pull request #8
Opened 2022-04-17 13:58 UTC by Oxunjon1029

2022-04-18 14:55 UTC, AudriusBaltusis requested changes
HW #9 description is `Cover 1 service with UT`. App component is not a service

2022-04-18 14:55 UTC, AudriusBaltusis commented on client/budgedtify/src/app/account/deletedialog/deletedialog.component.ts
> +const ID = new InjectionToken<string>('id', {
Is it used for share `accountId` between components?
For this functionality please create separate service and move there all localStorage based functionality (create methods `getAccountId` and `setAccountId`).

2022-04-18 23:57 UTC, Oxunjon1029 commented
I created test for auth service, I will address the next problem tomorrow.
Thanks for comments

On Mon, 18 Apr 2022 at 19:55, Audrius Baltušis ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> HW #9 description is Cover 1 service with UT. App component is not a
> service
> ------------------------------
>
> In
> client/budgedtify/src/app/account/deletedialog/deletedialog.component.ts
> <https://github.com/Oxunjon1029/budget/pull/8#discussion_r852170369>:
>
> >  import { AccountFrontService } from '../account-front.service';
>  import { Accounts } from '../accounts.interface';
> -
> +const ID = new InjectionToken<string>('id', {
>
> Is it used for share accountId between components?
> For this functionality please create separate service and move there all
> localStorage based functionality (create methods getAccountId and
> setAccountId).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Oxunjon1029/budget/pull/8#pullrequestreview-944480022>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULOQHDP6OAM2CU6GDSVFE3VFVZVVANCNFSM5TT5H5RA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-19 17:18 UTC, AudriusBaltusis approved these changes

2022-04-20 07:09 UTC, merged